security:
    enable_authenticator_manager: true  # Activer le gestionnaire d'authenticators pour Symfony 5.4 et plus

    password_hashers:
        App\Entity\User:
            algorithm: auto
        App\Entity\Vendor:
            algorithm: auto

    providers:
        in_memory: { memory: ~ }
        in_user:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Firewall pour l'authentification via /api/login
        login:
            pattern: ^/user/api/login
            stateless: true
            provider: in_user  # Fournisseur explicite pour les utilisateurs
            json_login:
                check_path: /user/api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour les autres routes API protégées par JWT
        api:
            pattern:   ^/user/api
            stateless: true
            provider: in_user  # Assure-toi que le même provider est utilisé ici si nécessaire
            jwt: ~  # Activer l'authentification JWT via Lexik JWT Authentication Bundle

    access_control:
        - { path: ^/user/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/api, roles: IS_AUTHENTICATED_FULLY }
