security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
        App\Entity\Vendor:
            algorithm: auto

    providers:
        in_memory: { memory: ~ }
        in_user:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        userAPILogin:
            pattern:  ^/user/api/login
            provider: in_user
            stateless: true
            json_login:
                check_path: /user/api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        userAPI:
            pattern: ^/user/api
            provider: in_user
            stateless: true
            custom_authenticators:
                - lexik_jwt_authentication.jwt_manager
            # optional authentication mechanisms you can activate:
            # http_basic: true
            # form_login: true

    access_control:
        - { path: ^/user/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/api,       roles: IS_AUTHENTICATED_FULLY }
