monolog:
    handlers:
        logtail:
            type: service
            id: Logtail\Monolog\LogtailHandler
            level: debug  # Capture tous les niveaux de logs


        # Logs also to stderr (for example, in Heroku or Docker)
        nested:
            type: stream
            path: "php://stderr"
            level: debug  # Capture tous les niveaux de logs

        # Handler for the Symfony console
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]  # Exclude event and doctrine logs
